# not using sudo
sudo: false

language: cpp

compiler:
  - gcc

before_script:
  - cmake --version
  - python --version

script: 
  - cd ..
  # compile against Orthanc v0.8.6
  - mkdir build086
  - cd build086
  - cmake -DORTHANC_VERSION=0.8.6 ../dwv-orthanc-plugin
  - make
  - cd ..
  # compile against Orthanc v0.9.6
  - mkdir build096
  - cd build096
  - cmake -DORTHANC_VERSION=0.9.6 ../dwv-orthanc-plugin
  - make
  - cd ..
  # compile against Orthanc v1.0.0
  - mkdir build100
  - cd build100
  - cmake -DORTHANC_VERSION=1.0.0 ../dwv-orthanc-plugin
  - make
  - cd ..
