# not using sudo
sudo: false

language: cpp

compiler:
  - gcc

before_script:
  - cmake --version
  - python --version

script: 
  - cd ..
  - mkdir build
  - cd build
  - cmake ../dwv-orthanc-plugin
  - make
